[package]
name = "sql-type"
version = "0.1.0"
edition = "2021"
authors = ["Jakob Truelsen <antialize@gmail.com>"]
keywords = [ "mysql", "sql", "typer" ]
license = "Apache-2.0"

[dev-dependencies]
codespan-reporting = "0.11"

[dependencies]
sql-ast = {path = "../sql-ast"}
