[package]
name = "sql-type"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
codespan-reporting = "0.11"

[dependencies]
sql-ast = {path = "../sql-ast"}
